# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Caronte Api Common Pakcage

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -U pip setuptools
          pip install poetry
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest ./tests
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -U pip setuptools
          pip install poetry
          poetry install
      - name: Source code analysis
        run: |
          poetry run pylint ./tests ./caronte_infra
